const Region = [
  { value: 'C', label: 'Central' },
  { value: 'N', label: 'North' },
  { value: 'S', label: 'South' },
  { value: 'CE', label: 'Central East' },
  { value: 'CW', label: 'Central West' },
  { value: 'NE', label: 'Northeast' },
];

const CSC = [
  {
    value: 'RMC Production and Service Metro 1',
    label: 'RMC Production and Service Metro 1',
    link: 'C',
  },
  {
    value: 'RMC Production and Service Metro 2',
    label: 'RMC Production and Service Metro 2',
    link: 'C',
  },
  {
    value: 'RMC Production and Service Metro 3',
    label: 'ARMC Production and Service Metro 3',
    link: 'C',
  },
  {
    value: 'RMC Production and Service Metro 4',
    label: 'RMC Production and Service Metro 4',
    link: 'C',
  },
  {
    value: 'CPAC Solution Center กรุงเทพฯ และปริมณฑล',
    label: 'CPAC Solution Center กรุงเทพฯ และปริมณฑล',
    link: 'C',
  },
  {
    value: 'CPAC Solution Center กระบี่',
    label: 'CPAC Solution Center กระบี่',
    link: 'S',
  },
  {
    value: 'CPAC Solution Center สุราษฎร์ธานี',
    label: 'CPAC Solution Center สุราษฎร์ธานี',
    link: 'S',
  },
  {
    value: 'CPAC Solution Center ภูเก็ต',
    label: 'CPAC Solution Center ภูเก็ต',
    link: 'S',
  },
  {
    value: 'CPAC Solution Center นครศรีธรรมราช',
    label: 'CPAC Solution Center นครศรีธรรมราช',
    link: 'S',
  },
  {
    value: 'CPAC Solution Center สงขลา',
    label: 'CPAC Solution Center สงขลา',
    link: 'S',
  },
  {
    value: 'CPAC Solution Center ฉะเชิงเทรา',
    label: 'CPAC Solution Center ฉะเชิงเทรา',
    link: 'CE',
  },
  {
    value: 'CPAC Solution Center ชลบุรี',
    label: 'CPAC Solution Center ชลบุรี',
    link: 'CE',
  },
  {
    value: 'CPAC Solution Center ระยอง',
    label: 'CPAC Solution Center ระยอง',
    link: 'CE',
  },
  {
    value: 'CPAC Solution Center สระบุรี',
    label: 'CPAC Solution Center สระบุรี',
    link: 'CE',
  },
  {
    value: 'CPAC Solution Center อยุธยา',
    label: 'CPAC Solution Center อยุธยา',
    link: 'CW',
  },
  {
    value: 'CPAC Solution Center นครปฐม',
    label: 'CPAC Solution Center นครปฐม',
    link: 'CW',
  },
  {
    value: 'CPAC Solution Center สมุทรสาคร',
    label: 'CPAC Solution Center สมุทรสาคร',
    link: 'CW',
  },
  {
    value: 'CPAC Solution Center ลำปาง',
    label: 'CPAC Solution Center ลำปาง',
    link: 'N',
  },
  {
    value: 'CPAC Solution Center เชียงใหม่',
    label: 'CPAC Solution Center เชียงใหม่',
    link: 'N',
  },
  {
    value: 'CPAC Solution Center เชียงราย',
    label: 'CPAC Solution Center เชียงราย',
    link: 'N',
  },
  {
    value: 'CPAC Solution Center พิษณุโลก',
    label: 'CPAC Solution Center พิษณุโลก',
    link: 'N',
  },
  {
    value: 'CPAC Solution Center นครสวรรค์',
    label: 'CPAC Solution Center นครสวรรค์',
    link: 'N',
  },
  {
    value: 'CPAC Solution Center นครราชสีมา',
    label: 'CPAC Solution Center นครราชสีมา',
    link: 'NE',
  },
  {
    value: 'CPAC Solution Center สกลนคร',
    label: 'CPAC Solution Center สกลนคร',
    link: 'NE',
  },
  {
    value: 'CPAC Solution Center อุดรธานี',
    label: 'CPAC Solution Center อุดรธานี',
    link: 'NE',
  },
  {
    value: 'CPAC Solution Center อุบลราชธานี',
    label: 'CPAC Solution Center อุบลราชธานี',
    link: 'NE',
  },
  {
    value: 'CPAC Solution Center ขอนแก่น',
    label: 'CPAC Solution Center ขอนแก่น',
    link: 'NE',
  },
];

const Province = [
  { value: 'BKK', label: 'กรุงเทพมหานคร', link: 'RMC Production and Service Metro 1' },
  { value: 'BKK', label: 'กรุงเทพมหานคร', link: 'RMC Production and Service Metro 2' },
  { value: 'SPK', label: 'สมุทรปราการ', link: 'RMC Production and Service Metro 2' },
  { value: 'NBI', label: 'นนทบุรี', link: 'RMC Production and Service Metro 2' },
  { value: 'BKK', label: 'กรุงเทพมหานคร', link: 'RMC Production and Service Metro 3' },
  { value: 'PTE', label: 'ปทุมธานี', link: 'RMC Production and Service Metro 3' },
  { value: 'BKK', label: 'กรุงเทพมหานคร', link: 'RMC Production and Service Metro 4' },
  { value: 'SPK', label: 'สมุทรปราการ', link: 'RMC Production and Service Metro 4' },
  { value: 'NBI', label: 'นนทบุรี', link: 'CPAC Solution Center กรุงเทพฯ และปริมณฑล' },
  { value: 'PTE', label: 'ปทุมธานี', link: 'CPAC Solution Center กรุงเทพฯ และปริมณฑล' },
  { value: 'KBI', label: 'กระบี่', link: 'CPAC Solution Center กระบี่' },
  { value: 'TRG', label: 'ตรัง', link: 'CPAC Solution Center กระบี่' },
  { value: 'SNI', label: 'สุราษฎร์ธานี', link: 'CPAC Solution Center สุราษฎร์ธานี' },
  { value: 'CPN', label: 'ชุมพร', link: 'CPAC Solution Center สุราษฎร์ธานี' },
  { value: 'PKT', label: 'ภูเก็ต', link: 'CPAC Solution Center ภูเก็ต' },
  { value: 'PNA', label: 'พังงา', link: 'CPAC Solution Center ภูเก็ต' },
  { value: 'NST', label: 'นครศรีธรรมราช', link: 'CPAC Solution Center นครศรีธรรมราช' },
  { value: 'PLG', label: 'พัทลุง', link: 'CPAC Solution Center นครศรีธรรมราช' },
  { value: 'SKA', label: 'สงขลา', link: 'CPAC Solution Center สงขลา' },
  { value: 'YLA', label: 'ยะลา', link: 'CPAC Solution Center สงขลา' },
  { value: 'CBI', label: 'ชลบุรี', link: 'CPAC Solution Center ฉะเชิงเทรา' },
  { value: 'CCO', label: 'ฉะเชิงเทรา', link: 'CPAC Solution Center ฉะเชิงเทรา' },
  { value: 'PRI', label: 'ปราจีนบุรี', link: 'CPAC Solution Center ฉะเชิงเทรา' },
  { value: 'SKW', label: 'สระแก้ว', link: 'CPAC Solution Center ฉะเชิงเทรา' },
  { value: 'CBI', label: 'ชลบุรี', link: 'CPAC Solution Center ชลบุรี' },
  { value: 'RYG', label: 'ระยอง', link: 'CPAC Solution Center ชลบุรี' },
  { value: 'RYG', label: 'ระยอง', link: 'CPAC Solution Center ระยอง' },
  { value: 'CTI', label: 'จันทบุรี', link: 'CPAC Solution Center ระยอง' },
  { value: 'TRT', label: 'ตราด', link: 'CPAC Solution Center ระยอง' },
  { value: 'SRI', label: 'สระบุรี', link: 'CPAC Solution Center สระบุรี' },
  { value: 'NYK', label: 'นครนายก', link: 'CPAC Solution Center สระบุรี' },
  { value: 'AYA', label: 'พระนครศรีอยุธยา', link: 'CPAC Solution Center อยุธยา' },
  { value: 'ATG', label: 'อ่างทอง', link: 'CPAC Solution Center อยุธยา' },
  { value: 'CNT', label: 'ชัยนาท', link: 'CPAC Solution Center อยุธยา' },
  { value: 'SPB', label: 'สุพรรณบุรี', link: 'CPAC Solution Center อยุธยา' },
  { value: 'NPT', label: 'นครปฐม', link: 'CPAC Solution Center นครปฐม' },
  { value: 'SKN', label: 'สมุทรสาคร', link: 'CPAC Solution Center นครปฐม' },
  { value: 'RBR', label: 'ราชบุรี', link: 'CPAC Solution Center นครปฐม' },
  { value: 'KRI', label: 'กาญจนบุรี', link: 'CPAC Solution Center นครปฐม' },
  { value: 'PBI', label: 'เพชรบุรี', link: 'CPAC Solution Center สมุทรสาคร' },
  { value: 'PKN', label: 'ประจวบคีรีขันธ์', link: 'CPAC Solution Center สมุทรสาคร' },
  { value: 'SKM', label: 'สมุทรสงคราม', link: 'CPAC Solution Center สมุทรสาคร' },
  { value: 'SKN', label: 'สมุทรสาคร', link: 'CPAC Solution Center สมุทรสาคร' },
  { value: 'LPG', label: 'ลำปาง', link: 'CPAC Solution Center ลำปาง' },
  { value: 'TAK', label: 'ตาก', link: 'CPAC Solution Center ลำปาง' },
  { value: 'KPT', label: 'กำแพงเพชร', link: 'CPAC Solution Center ลำปาง' },
  { value: 'CMI', label: 'เชียงใหม่', link: 'CPAC Solution Center เชียงใหม่' },
  { value: 'LPN', label: 'ลำพูน', link: 'CPAC Solution Center เชียงใหม่' },
  { value: 'MSN', label: 'แม่ฮ่องสอน', link: 'CPAC Solution Center เชียงใหม่' },
  { value: 'CRI', label: 'เชียงราย', link: 'CPAC Solution Center เชียงราย' },
  { value: 'PYO', label: 'พะเยา', link: 'CPAC Solution Center เชียงราย' },
  { value: 'PRE', label: 'แพร่', link: 'CPAC Solution Center เชียงราย' },
  { value: 'NAN', label: 'น่าน', link: 'CPAC Solution Center เชียงราย' },
  { value: 'STI', label: 'สุโขทัย', link: 'CPAC Solution Center พิษณุโลก' },
  { value: 'PLK', label: 'พิษณุโลก', link: 'CPAC Solution Center พิษณุโลก' },
  { value: 'UTT', label: 'อุตรดิตถ์', link: 'CPAC Solution Center พิษณุโลก' },
  { value: 'NSN', label: 'นครสวรรค์', link: 'CPAC Solution Center นครสวรรค์' },
  { value: 'UTI', label: 'อุทัยธานี', link: 'CPAC Solution Center นครสวรรค์' },
  { value: 'PCT', label: 'พิจิตร', link: 'CPAC Solution Center นครสวรรค์' },
  { value: 'NMA', label: 'นครราชสีมา', link: 'CPAC Solution Center นครราชสีมา' },
  { value: 'CPM', label: 'ชัยภูมิ', link: 'CPAC Solution Center นครราชสีมา' },
  { value: 'NPM', label: 'นครพนม', link: 'CPAC Solution Center สกลนคร' },
  { value: 'SNK', label: 'สกลนคร', link: 'CPAC Solution Center สกลนคร' },
  { value: 'MDH', label: 'มุกดาหาร', link: 'CPAC Solution Center สกลนคร' },
  { value: 'YST', label: 'ยโสธร', link: 'CPAC Solution Center สกลนคร' },
  { value: 'UDN', label: 'อุดรธานี', link: 'CPAC Solution Center อุดรธานี' },
  { value: 'NBP', label: 'หนองบัวลำภู', link: 'CPAC Solution Center อุดรธานี' },
  { value: 'LEI', label: 'เลย', link: 'CPAC Solution Center อุดรธานี' },
  { value: 'KKN', label: 'ขอนแก่น', link: 'CPAC Solution Center อุดรธานี' },
  { value: 'BKN', label: 'บึงกาฬ', link: 'CPAC Solution Center อุดรธานี' },
  { value: 'SRN', label: 'สุรินทร์', link: 'CPAC Solution Center อุบลราชธานี' },
  { value: 'UBN', label: 'อุบลราชธานี', link: 'CPAC Solution Center อุบลราชธานี' },
  { value: 'BRM', label: 'บุรีรัมย์', link: 'CPAC Solution Center อุบลราชธานี' },
  { value: 'KKN', label: 'ขอนแก่น', link: 'CPAC Solution Center ขอนแก่น' },
  { value: 'MKM', label: 'มหาสารคาม', link: 'CPAC Solution Center ขอนแก่น' },
  { value: 'RET', label: 'ร้อยเอ็ด', link: 'CPAC Solution Center ขอนแก่น' },
  { value: 'KSN', label: 'กาฬสินธุ์', link: 'CPAC Solution Center ขอนแก่น' },
];

export { Region, CSC, Province };
